version: 2.1
orbs:
  cypress: cypress-io/cypress@2.2.0
workflows:
  build:
    jobs:
        - cypress/install
        - cypress/run:
            requires:
            - cypress/install
            store_artifacts: true
            parallel: true
            parallelism: 2
            steps:
              - run: go test -v $(go list ./... | circleci tests split --split-by=timings)
            group: 2 machines

